# dar-nixos: a minimal NixOS machine, described in one file.
#
# Companion to https://abdelhousni.github.io/til/nixos/first-steps-configuration-generations-rollback.html
#
# On a real machine this file lives at /etc/nixos/configuration.nix, next to
# the hardware-configuration.nix that `nixos-generate-config` wrote for you.
# To try it without installing anything, build it as a VM (see README.md).
{ config, pkgs, ... }:

{
  # Real hardware: disks, filesystems and kernel modules. Generated by the
  # installer, specific to one machine, so it isn't committed here. The VM
  # build doesn't need it; it brings its own virtual disk.
  imports =
    [ ./zsh.nix   # Zsh + Oh My Zsh, see zsh.nix
      ./ccbox.nix # coding agents in rootless Podman, see ccbox.nix
    ]
    ++ (if builtins.pathExists ./hardware-configuration.nix
        then [ ./hardware-configuration.nix ]
        else [ ]);

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Every rebuild adds a boot entry. Cap how many stay in the menu so /boot
  # doesn't fill up; older generations still exist in /nix until collected.
  boot.loader.systemd-boot.configurationLimit = 10;

  networking.hostName = "dar-nixos";
  time.timeZone = "UTC";

  # Packages: declared here, not installed with nix-env.
  environment.systemPackages = with pkgs; [
    git
    htop
  ];

  # A service is a module, not just a package: this writes the systemd unit,
  # sshd_config and the firewall rule for port 22.
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
    };
  };

  users.users.demo = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    # Add your own public key to log in over SSH:
    # openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA... you@laptop" ];
  };

  # Weekly garbage collection that keeps two weeks of generations to roll
  # back to. `nix-collect-garbage -d` would delete them all.
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # Settings that only apply to `nixos-rebuild build-vm` / the vm attribute.
  virtualisation.vmVariant = {
    virtualisation.memorySize = 2048;
    virtualisation.forwardPorts = [
      { from = "host"; host.port = 2222; guest.port = 22; }
    ];
    # Throwaway password so you can log in at the VM console. VM only.
    users.users.demo.initialPassword = "demo";
  };

  # The NixOS release this machine was FIRST installed with. It is not the
  # version you are running, and bumping it does not upgrade anything.
  # Leave it alone after the first install.
  system.stateVersion = "26.05";
}
